import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { Container } from "../components/pageComponents/global/style";
import Helmet from "../components/utils/Header/Helmet";
import Landing from "./Landing";

export default function Home() {
  const loggedIn = useSelector((state) => state.login.success);
  const router = useRouter();

  useEffect(() => {
    if (!loggedIn) {
      router.push("/Login");
    }
  }, [loggedIn, router])
  return (
    <div>
      <Head>
        <title>DOC-UPI-Doctor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Helmet />
        <Landing />
      </Container>
    </div>
  );
}
