import Head from "next/head";
import { Container } from "../components/pageComponents/global/style";
import Helmet from "../components/utils/Header/Helmet";
import Landing from "./Landing";
import SignUp from "./SignUp";

export default function Home() {
  const loggedIn = true;
  return (
    <div>
      <Head>
        <title>DOC-UPI-Doctor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Helmet />
        {loggedIn ? <Landing /> : <SignUp />}
      </Container>
    </div>
  );
}
